# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_name',
            field=models.CharField(max_length=200),
        ),
    ]
