# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160507_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_failed',
            field=models.NullBooleanField(),
        ),
    ]
